### ISSUE TITLE
Pending layers

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/PRN-maps#17]
Pending layers (awaiting approval) for an event can be viewed at the moment by adding `pending=true` to an event's URL eg. https://prn-maps.planetaryresponsenetwork.org/maps/?event=dominica_2018_demo&pending=true (password protected.)

Pending layers should also show a button that POSTs to `/pending/layers/${event_name}/approve` to approve all pending layers for the event. See [zooniverse/PRN-maps-api](https://github.com/zooniverse/PRN-maps-api) for details of the API.

**Comment by shaunanoordin** [comment]
This feature has now been added via PR #18 and #20
