### ISSUE TITLE
show all event layers on first load

### ISSUE THREAD

**Issue by camallen** [zooniverse/PRN-maps#23]
I've got a few island layers setup but the map zooms in on 1 island instead of showing all layers via an overview. https://prn-maps.planetaryresponsenetwork.org/maps/?pending=true&event=dominica_2018_demo

We can use the event ROI information to derive a source bounding box instead of calculating it from the data layers...
https://maps-api.planetaryresponsenetwork.org/events/dominica_2018_demo
```
{"date":"2019/01/09","name":"Dominca 2018 Demo","bounding_box_coords":[-61.577664,15.185255,-61.143342,15.673547],"geotiff_source_imagery":{"before_image_file_name":"dominica_planet_before.tif","before_image_provider":"dg","after_image_file_name":"dominica_planet_after.tif","after_image_provider":"dg"},"zooniverse_metadata":{"project_id":2419,"subject_set_id":60320},"s3_metadata":{"bucket_name":"planetary-response-network","bucket_path":"dominca_2018","bucket_host_name":"planetary-response-network.s3.amazonaws.com"}}
```

Current behaviour

<img width="1092" alt="Screenshot 2019-03-19 at 13 47 14" src="https://user-images.githubusercontent.com/295329/54610825-b3251580-4a4d-11e9-8142-ce8db885b3ab.png">

Closer to desired

<img width="1154" alt="Screenshot 2019-03-19 at 13 48 28" src="https://user-images.githubusercontent.com/295329/54610858-cc2dc680-4a4d-11e9-8d7a-2150b2cdf9d9.png">

**Comment by eatyourgreens** [comment]
Map bounds are set here, after a single layer has loaded:
https://github.com/zooniverse/PRN-maps/blob/c43a500ddb36bae54b9302c9e07c8e103d61d20b/js/maps.js#L152-L159

The fix is probably as simple as waiting for all layers to be added before calculating the map bounds.
