### ISSUE TITLE
pending layers should show all available

### ISSUE THREAD

**Issue by camallen** [zooniverse/PRN-maps#25]
linked to #24 - the bounding box for pending layers seems to be calculated from the first layer only. either do the same as #24 or we do it for all layers.

**Comment by eatyourgreens** [comment]
Weird. #24 removed all that code.

**Comment by eatyourgreens** [comment]
https://prn-maps.planetaryresponsenetwork.org/maps/?event=caribbean_2018_demo?pending=true shows the whole Caribbean for me.

**Comment by shaunanoordin** [comment]
What Jim said 👍 - confirmed on my end too.

![Screen Shot 2019-03-19 at 16 26 41](https://user-images.githubusercontent.com/13952701/54623626-cfcc4800-4a63-11e9-9584-60d462cdf399.png)
_Initial map view. Note that it took a second for the map to fetch the metadata-defined initial map bounds. If this fetch could not be made (e.g. if the WiFi dropped down JUST as we were asking the '/events' endpoint), the map default to [an arbitrary point near the island of Dominica](https://www.google.com/maps/place/15%C2%B013'53.3%22N+61%C2%B015'02.6%22W/@15.2314633,-61.2529055,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d15.2314581!4d-61.2507115)_

**Comment by camallen** [comment]
my apologies, this is indeed working correctly now.
