### ISSUE TITLE
Ensure we zoom to the new regions when changing AOIs / layer versions

### ISSUE THREAD

**Issue by camallen** [zooniverse/PRN-maps#44]
If I zoom to fit one layer AOI, i can see the heatmap data nicely in the map. However if i select another AOI layer from the published list on the left, the map display doesn't shift to bring the new data into view. 

Reproducable with the current data https://prn-maps.planetaryresponsenetwork.org/maps/?event=caribbean_2018_demo

Click V5 and 'Zoom to fit', then V2 road blockage layer

I have to repress 'Zoom to fit' button to see the data.

**Comment by shaunanoordin** [comment]
Auto-zoomfitting (yes, that's a verb now) the map view every time the user selects a new layer isn't always a good idea, as certain layers that should logically be 'next' to each other can cause jittering when a user just wants to compare between those two adjacent layers.

![prn-maps-issue-44-jitter](https://user-images.githubusercontent.com/13952701/62064082-068d4880-b224-11e9-963d-b60ecbdc2307.gif)
_Jittering as the result of auto-zoomfitting when moving back/forth between Structural Damage and Flooding layers_

Same problem if the user is looking at _different zoom levels;_ when trying to compare layers, they'll always be reset to the 'full zoom' level.

A possible improvement to the proposed solution is to have an "auto-zoom-to-fit" checkbox that can be switched off (default: on) should the user wish to compare two layers, OR only automatically zoom-to-fit _when choosing a different version group._

**Comment by shaunanoordin** [comment]
Wait, re-reading the original issue, I realise that "AOI" actually meant version group and not the individual layers, which meant that the proposal @camallen was talking about matched exactly with _"only automatically zoom-to-fit when choosing a different version group."_ Whoops, sorry!

But anyway, the upgrade is already in the works 👍
