### ISSUE TITLE
Add PRN events overview landing page

### ISSUE THREAD

**Issue by camallen** [zooniverse/PRN-maps#6]
As a user i want to select an event from a list to display data for a selected event.

It might be worth thinking about how we present lots of events / how we search for events in the longer term. Short term (prototype) i think it's ok to list them out. 

I.e. should event API data be at a higher level? Instead of an event for Caribbean Dominica data, should it just be Caribbean 2018 event that contains all the different data layers (dominica, turks & caicos, etc)?

**Comment by eatyourgreens** [comment]
#9 made a start on adding a simple events listing page.

**Comment by eatyourgreens** [comment]
Re-opening this because #9 shouldn't have closed it.

**Comment by camallen** [comment]
closing for now - will revisit this after feedback from teams that use the UI.
