### ISSUE TITLE
Add ability to upload new layer files and metadata from a UI form

### ISSUE THREAD

**Issue by camallen** [zooniverse/PRN-maps#7]
As an approved user, I want to be able to access a form to select my layer data files and input the layer(s) metadata via a JSON text string. The form will submit to the API to load the files / data into the pending S3 paths.

This API route will require basic authentication, handled by the browser

**Comment by eatyourgreens** [comment]
This could just be a HTML form that submits to the endpoint. It might not need any JavaScript beyond simple input validation.

**Comment by eatyourgreens** [comment]
Is the API endpoint set up for this? Do you know what the POST request payload should look like?

Basic file upload can be handled by `<input type=file />`, if the endpoint accepts form-encoded file contents. I'm not sure about the JSON text string bit, though, so we'll need some more details about that.

**Comment by camallen** [comment]
No API end point yet. It'll need to an authenticated end point though to ensure only folks like steve can upload data to it. 

If we know the metadata we want to control we can split it out to form fields. I'm not sure we know enough yet so i was thinking that the JSON metadata can be a client side linted text field string. API can decode that to JSON on server side for storage in s3 object. Issues with that?

**Comment by camallen** [comment]
thanks to @eatyourgreens we can just have two form file inputs 1 for the csv layer data, 1 for the associated metadata
